# Generated by Django 3.2.5 on 2021-07-15 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conexao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('para', models.TextField()),
                ('assunto', models.TextField(blank=True, null=True)),
                ('mensagem', models.TextField(blank=True, null=True)),
                ('de', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails_enviados', to='api.conexao')),
            ],
        ),
    ]
